### ISSUE TITLE
One note at a time

### ISSUE THREAD

**Issue by MaxScorda** [nathanRamaNoodles/MusicWithoutDelay-LIbrary#4]
Hi, I have a question: Is there a way to play a song with one note at a time?
I've got a project of generative music so song it's empty at start  and I create one note at a time and i would like to play note then create another note, play it and so on. I try with NewSong everytime with a new song but  it don't work. Could you show me an example?
Thank you 
Max

**Comment by nathanRamaNoodles** [comment]
Whoops, sorry for the long delay.  My email notifications weren't working.  It works now.

Anyway, my library doesn't support recording at the moment.  I think that is what you are saying.
Show me your code, so I can better understand your situation.

At the moment, I believe you can have multiple pre-defined `song *char` and make each set equal a different note.  For example,  using the "newSong sketch", we can try the following arrays:
`
char *note  = ":d=8:c";  //we can make all notes into eight notes, since we are using the same MusicWithoutDelay object
char *note2 = "::d";     //so we don't have to redeclare d=8 over and over again.
char *note3 = "::e";
char *note4 = "::f";
#define numberOfNotes 4
int noteCount = 1;
char *song[] = {note, note2, note3, note4};
`

Check the attached file for the full code.  It should play one song, one note after another(four notes in total).
[One_note_at_a_time.zip](https://github.com/nathanRamaNoodles/MusicWithoutDelay-LIbrary/files/1989211/One_note_at_a_time.zip)
